# Cấu hình thời gian nhận thưởng mỗi cấp độ (giây)
time_per_level:
  level1: 60     # Cấp độ 1: 60 giây
  level2: 50     # Cấp độ 2: 50 giây
  level3: 40     # Cấp độ 3: 40 giây
  level4: 30     # Cấp độ 4: 30 giây
  level5: 20     # Cấp độ 5: 20 giây

# Cấu hình các vật phẩm nhận được (ID item, số lượng, tỉ lệ)
items:
  - id: 264    # Diamond
    amount: 1
    chance: 50  # Tỉ lệ 50%
  - id: 265    # Iron Ingot
    amount: 3
    chance: 30  # Tỉ lệ 30%
  - id: 266    # Gold Ingot
    amount: 2
    chance: 20  # Tỉ lệ 20%

# Cấu hình các lệnh (lệnh, tỉ lệ, số lần lặp)
commands:
  - command: "say {player} received a reward!"
    chance: 50  # Tỉ lệ 50%
    repeat: 1   # Lặp 1 lần
  - command: "give {player} minecraft:stone 5"
    chance: 30  # Tỉ lệ 30%
    repeat: 2   # Lặp 2 lần
  - command: "give {player} minecraft:wooden_sword 1"
    chance: 20  # Tỉ lệ 20%
    repeat: 3   # Lặp 3 lần

# Thông báo khi người chơi quay lại
message: "§aBạn đã trở lại sau §b{days} ngày, §e{hours} giờ, §7{minutes} phút và nhận được §6{rewards} vật phẩm!"
